# Generated by Django 3.2.8 on 2021-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.CharField(choices=[('Présentiel', 'Présentiel'), ('Visio', 'Visio')], max_length=100, null=True)),
                ('question', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=128)),
                ('teacher', models.CharField(max_length=128)),
                ('organization1', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('organization2', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('organization3', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('formation1', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('formation2', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('formation3', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('formation4', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('formation5', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('formation6', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('teacher1', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('teacher2', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('teacher3', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('teacher4', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('apprecition1', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('apprecition2', models.CharField(choices=[('Pas du tou', '1'), ('Oui plutôt', '2'), ('Tout à fait', '3')], max_length=100)),
                ('recommandation1', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=100)),
                ('recommandation2', models.CharField(max_length=100)),
                ('formation_want1', models.CharField(choices=[('CSE', 'CSE'), ('SSCT', 'SSCT'), ('Référent harcèlement', 'Référent harcèlement'), ('Représentant de proximité', 'Représentant de proximité'), ('DUERP', 'DUERP'), ('AUTRES:', 'DUERP,')], max_length=100)),
                ('formation_want2', models.CharField(choices=[('CSE', 'CSE'), ('SSCT', 'SSCT'), ('Référent harcèlement', 'Référent harcèlement'), ('Représentant de proximité', 'Représentant de proximité'), ('DUERP', 'DUERP'), ('AUTRES:', 'DUERP,')], max_length=100)),
                ('formation_want3', models.CharField(choices=[('CSE', 'CSE'), ('SSCT', 'SSCT'), ('Référent harcèlement', 'Référent harcèlement'), ('Représentant de proximité', 'Représentant de proximité'), ('DUERP', 'DUERP'), ('AUTRES:', 'DUERP,')], max_length=100)),
                ('formation_want4', models.CharField(choices=[('CSE', 'CSE'), ('SSCT', 'SSCT'), ('Référent harcèlement', 'Référent harcèlement'), ('Représentant de proximité', 'Représentant de proximité'), ('DUERP', 'DUERP'), ('AUTRES:', 'DUERP,')], max_length=100)),
                ('formation_want5', models.CharField(choices=[('CSE', 'CSE'), ('SSCT', 'SSCT'), ('Référent harcèlement', 'Référent harcèlement'), ('Représentant de proximité', 'Représentant de proximité'), ('DUERP', 'DUERP'), ('AUTRES:', 'DUERP,')], max_length=100)),
                ('formation_want6', models.CharField(choices=[('CSE', 'CSE'), ('SSCT', 'SSCT'), ('Référent harcèlement', 'Référent harcèlement'), ('Représentant de proximité', 'Représentant de proximité'), ('DUERP', 'DUERP'), ('AUTRES:', 'DUERP,')], max_length=100)),
                ('formation_type1', models.CharField(choices=[('Assistance juridique', 'Assistance juridique'), ('Communication / négociation', 'Communication / négociation'), ('Expertise SSCT', 'Expertise SSCT'), ('Expertise comptable', 'Expertise comptable'), ('Autres:', 'Autres:')], max_length=100)),
                ('formation_type2', models.CharField(choices=[('Assistance juridique', 'Assistance juridique'), ('Communication / négociation', 'Communication / négociation'), ('Expertise SSCT', 'Expertise SSCT'), ('Expertise comptable', 'Expertise comptable'), ('Autres:', 'Autres:')], max_length=100)),
                ('formation_type3', models.CharField(choices=[('Assistance juridique', 'Assistance juridique'), ('Communication / négociation', 'Communication / négociation'), ('Expertise SSCT', 'Expertise SSCT'), ('Expertise comptable', 'Expertise comptable'), ('Autres:', 'Autres:')], max_length=100)),
                ('formation_type4', models.CharField(choices=[('Assistance juridique', 'Assistance juridique'), ('Communication / négociation', 'Communication / négociation'), ('Expertise SSCT', 'Expertise SSCT'), ('Expertise comptable', 'Expertise comptable'), ('Autres:', 'Autres:')], max_length=100)),
                ('formation_type5', models.CharField(choices=[('Assistance juridique', 'Assistance juridique'), ('Communication / négociation', 'Communication / négociation'), ('Expertise SSCT', 'Expertise SSCT'), ('Expertise comptable', 'Expertise comptable'), ('Autres:', 'Autres:')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkboxeshelpanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='radioanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='recommandationanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='typeanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='CheckboxesAnswer',
        ),
        migrations.DeleteModel(
            name='CheckboxesHelpAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='RadioAnswer',
        ),
        migrations.DeleteModel(
            name='RecommandationAnswer',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
        migrations.DeleteModel(
            name='TypeAnswer',
        ),
    ]
