# Generated by Django 3.2.8 on 2021-11-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20211027_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='fc',
        ),
        migrations.AddField(
            model_name='quiz',
            name='stage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
