# Generated by Django 3.2.8 on 2021-11-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20211114_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='student_name',
            new_name='stage_name',
        ),
    ]
