# Generated by Django 3.2.8 on 2021-11-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_rename_student_name_quiz_stage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='location',
            new_name='place',
        ),
    ]
