# Generated by Django 3.2.8 on 2021-12-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20211202_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='apprecition1',
            new_name='appreciation1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='apprecition2',
            new_name='appreciation2',
        ),
    ]
