# Generated by Django 3.2.8 on 2021-12-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20211202_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='recommandation1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='recommandation2',
        ),
        migrations.AddField(
            model_name='quiz',
            name='recommendation1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='recommendation2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
