# Generated by Django 3.2.8 on 2021-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_auto_20211203_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='formation_type1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_type2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_type3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_type4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_type5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_want1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_want2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_want3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_want4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_want5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation_want6',
        ),
        migrations.AddField(
            model_name='quiz',
            name='other_formation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='other_formation_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
