# Generated by Django 3.2.8 on 2021-12-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_auto_20211203_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='other_formation',
            new_name='other_formation1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='other_formation_type',
            new_name='other_formation_type1',
        ),
        migrations.AddField(
            model_name='quiz',
            name='other_formation_type2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
