# Generated by Django 3.2.8 on 2021-12-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_auto_20211203_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='election_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
