# Generated by Django 3.2.8 on 2021-12-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_auto_20211203_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='stage_name',
        ),
    ]
