# Generated by Django 3.2.8 on 2021-12-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_remove_quiz_stage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='stage',
            new_name='stages',
        ),
    ]
