# Generated by Django 3.2.8 on 2021-12-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_rename_stage_quiz_stages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='stages',
            new_name='stage',
        ),
        migrations.AddField(
            model_name='quiz',
            name='stage_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
