# Generated by Django 3.2.8 on 2021-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_alter_quiz_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='other_formation2',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('SSCT', 'SSCT'), ('Référent harcèlement', 'Référent harcèlement'), ('Représentant de proximité', 'Représentant de proximité'), ('DUERP', 'DUERP'), ('AUTRES', 'AUTRES')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='appreciation1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='appreciation2',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='find',
            field=models.CharField(blank=True, choices=[('Site internet', 'Site internet'), ('Mailing', 'Mailing'), ('Entreprise ayant déjà participé à un stage SICOGE', 'Entreprise ayant déjà participé à un stage SICOGE'), ('Autre', 'Autre')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formation1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formation2',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formation3',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formation4',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formation5',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='formation6',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='organization1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='organization2',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='organization3',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='other_formation1',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='other_formation_type1',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='other_formation_type2',
            field=models.CharField(blank=True, choices=[('Assistance juridique', 'Assistance juridique'), ('Communication / négociation', 'Communication / négociation'), ('Expertise SSCT', 'Expertise SSCT'), ('Expertise comptable', 'Expertise comptable'), ('Autres', 'Autres')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='recommendation1',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher2',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher3',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher4',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True),
        ),
    ]
