# Generated by Django 3.2.8 on 2021-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_auto_20211206_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
