# Generated by Django 3.2.8 on 2021-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_auto_20211206_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='find',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='other_formation2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='other_formation_type2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
