# Generated by Django 3.2.8 on 2021-12-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_auto_20211206_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='organization1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
